### ISSUE TITLE
Fix FixedProcessFlow - stopping sometimes throws an exception

### ISSUE THREAD

**Issue by mnikliborc** [CommBank/parlour#53]
From time to time FixedProcessFlowSpec fails:

[info] FixedProcessFlowSpec
[info] ====================
[info]   + complete runs synchronously and calls onComplete
[info]   + start runs asynchronously and calls onComplete
[info]   + exception causes onThrowable than onComplete
[info]   x stop causes onStopped than onComplete
[error]  List(OnStopping, OnThrowable, OnCompleted)
[error]   is not equal to 
[error]  List(OnStarting, OnStopping, OnCompleted); List(OnStopping, OnThrowable, OnCompleted)
[error]   is not equal to 
[error]  List(OnStopping, OnStarting, OnCompleted); List(OnStopping, OnThrowable, OnCompleted) is not equal to List(OnStopping, OnCompleted); List(OnStopping, OnThrowable, OnCompleted) is not equal to List(OnCompleted, OnStopping) (FixedProcessFlowSpec.scala:82)
[error] Expected: ...(OnSt[art]in...On[St]o[pping], OnC...
[error] Actual:   ...(OnSt[opp]in...On[Thr]o[wable], OnC...

It seems like a race condtion. 

I lost printed stacktrace (if there was any), sorry:-) I'll post it when I get it again.

**Comment by stephanh** [comment]
No longrt using FixedProcessFlow.
