### ISSUE TITLE
Input Null String Not recognizing  hive null string format in Parlour Export

### ISSUE THREAD

**Issue by cherianhormis** [CommBank/parlour#62]
While doing export using parlour the hive null string (\N) is not getting replaced as NULL even though input null string is specified as "\\\\N".

**Comment by rowandavies** [comment]
I'm looking into this, but I really need a test that reproduces the issue in order to trace through why the replacement isn't happening within the sqoop API.

**Comment by vineethvarghese** [comment]
There should be some test around the null string if not we should add one.

-V
